version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      package-patch-minor:
        update-types: ["patch", "minor"]
      package-major:
        update-types: ["major"]
    commit-message:
      prefix: "chore"
