packages:
  - "."

minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: no-downgrade

overrides:
  vite: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
