name: Scan

on:
  pull_request:
  schedule:
    - cron: "41 6 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: scan-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    permissions:
      contents: read
    uses: putdotio/.github/.github/workflows/frontend-scan.yml@1ee0d3b473cbc6fada08831f01ff80fe653c434a # v1.1.0
